# Generated by Django 4.1.7 on 2023-04-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_id_usuario_partidas_id_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidas',
            name='nivel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
