# Generated by Django 4.1.7 on 2023-04-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_partidas_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidas',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
